### ISSUE TITLE
How do I add new users to Github

### ISSUE THREAD

**Issue by Deborahvdp** [uq-eresearch/qldarch-frontend#136]
I have a number of summer scholars working on the archive over the break and it would be good to add them to Github. 

They are: 

Miss Renee Bourke <renee.bourke@uqconnect.edu.au>
Miss Nicola White <nicola.white@uq.net.au>
Miss Sian Murphy <sian.murphy@uqconnect.edu.au>
Lloyd Jones <lloyd_jones11@hotmail.com>

**Comment by cmcnamara87** [comment]
@Deborahvdp now that I have added you as a collaborator on the Github, you can add the them once they sign up. The Github is public, so as soon as they sign up, they will be able to add issues, but if you do want them to be able to add labels, you will have to add them as collaborators. I've put the steps below:

* Go to the main QLDArch github page: https://github.com/uq-eresearch/qldarch-frontend
* Click 'Settings' on the right hand side of the page
* Click 'Collaborators' on the left of the page
* Click 'QLDArch'
* There is a text box in the top right that says 'Invite or add users to team'. You can type in their Github usernames there, and add them to our QLDArch group.
* That should be it :smile:
