### ISSUE TITLE
slow search when annotating

### ISSUE THREAD

**Issue by atjmacar** [uq-eresearch/qldarch-frontend#138]
when annotating, or linking architects to firms, projects to architects etc...the search function is progressive so that it looks of  all 'john's while still typing 'John Dalton' this slows things down. Can it work so that one completes the search term then presses enter?

**Comment by cmcnamara87** [comment]
Okay I'll look into that. I'll be able to wait for ```X``` seconds before showing possible results, that should speed things up.

**Comment by cmcnamara87** [comment]
Tried to speed it up a little.
