### ISSUE TITLE
Add URIs to search results

### ISSUE THREAD

**Issue by cmcnamara87** [uq-eresearch/qldarch-frontend#157]
The URL format for pages is currently
`http://localhost:9000/#/architect/summary?architectId=aHR0cDovL3FsZGFyY2gubmV0L3BlcnNvbi82NzI%3D` (as disgusting as it is).

The architect Id is basically an encoded version of this `http://qldarch.net/person/672`, which is the entities URI (in this case its Graham Bligh). 

In the search results page, it returns the `id` as just `672` but it would be a lot easier if it returned  the whole URI (so there is less front end logic, and eventually, you can just change all the URIs to be numbers, or even slugs).

**Comment by agebe** [comment]
I've added a common field 'uri' to all search documents that contains the type and id in uri format that can be passed to the webservice to load the object.
