### ISSUE TITLE
Articles tab uses solr search

### ISSUE THREAD

**Issue by agebe** [uq-eresearch/qldarch-frontend#159]
Clicking on the Articles tab on the Architects page returns id uris that are not working with the new webservices. Please use the new search api instead.

**Comment by agebe** [comment]
The articles are now in the search index.

**Comment by cmcnamara87** [comment]
In your email you say use `http://localhost:9000/ws/search?q=type:article&pretty&pc=1000`, how do I search for articles about Richard Allom instead of just all articles?

**Comment by cmcnamara87** [comment]
Got it working. Can you use camel case in the json?
```
  "periodicaltitle": "Architectural Design",
```
to 
```
  "periodicalTitle": "Architectural Design",
```

**Comment by agebe** [comment]
changed field names to camel case also for the other fields and types.

**Comment by agebe** [comment]
it is working on the architects and projects page but on the firm page is seems to get stuck on the current tab and won't switch to the articles. I can't see any errors in the console.

**Comment by cmcnamara87** [comment]
This articles tab loads fine for me

http://qldarch-test.metadata.net/beta/#/firm/articles?firmId=aHR0cDovL3FsZGFyY2gubmV0L3JkZi8yMDEyLTEyL3Jlc291cmNlcy9maXJtcy8x

Can you point to one in particular that wont load?

**Comment by cmcnamara87** [comment]
Hmm actually, I'm not sure what is happening with that one. I'll have a look
