### ISSUE TITLE
New timelines, word clouds and map should user displayname

### ISSUE THREAD

**Issue by agebe** [uq-eresearch/qldarch-frontend#171]
creating new timelines, word clouds or maps use the app users email address but should use the display name. see [test system](http://qldarch-test.metadata.net/) and scroll down to the Gallery. E.g. first timeline reads "Plans for A Subtropical Climate By **email-address**" but should be display name

**Comment by fdpambu** [comment]
12ef0c00ac4b71cefccc7f326155d317c3af3862
