### ISSUE TITLE
postwar@architecture.uq.edu.au still valid?

### ISSUE THREAD

**Issue by agebe** [uq-eresearch/qldarch-frontend#172]
Clicking on the Email button on the front page (below Get in touch, scroll down to the bottom of the page) brings up a new email window to postwar@architecture.uq.edu.au I think this email address is no longer monitored. Find out if this is true and change the email address if required.

**Comment by fdpambu** [comment]
c7b25280044d89e58bb8cae0d35325521fb5b124
