### ISSUE TITLE
Covering statement for architects bios

### ISSUE THREAD

**Issue by Deborahvdp** [uq-eresearch/qldarch-frontend#35]
Can we have a covering statement for all bios stating that the bios are summaries of the interviews only?

**Comment by cmcnamara87** [comment]
Sure. Do you have something in mind?

**Comment by Deborahvdp** [comment]
Something along the lines of: content of biography has been extracted from interviews only. If external sources are used, they are acknowledged in the bibliography following the entry.

**Comment by Deborahvdp** [comment]
Sorry, this item is still open. I hit the wrong button.
